[tools]
bun = "latest"
rust = { version = "1.96.1", profile = "default" }

[tasks.dev]
description = "Start RedNotes Plus in dev mode"
run = "cd app && bun tauri dev"

[tasks.build]
description = "Build RedNotes Plus"
run = "cd app && bun tauri build"
