[tools]
bun = "latest"
rust = { version = "1.97.0", profile = "default" }

[tasks.dev]
description = "Start RedNotes Plus in dev mode"
run = "cd app && bun tauri dev"

[tasks.build]
description = "Build RedNotes Plus"
run = "cd app && bun tauri build"

[tasks.check]
description = "Check Rust code using cargo check and cargo clippy"
depends = ["check-common","check-main"]

[tasks.check-common]
run = "cd common && cargo check && cargo clippy"

[tasks.check-main]
run = "cd app && cargo check && cargo clippy"
