[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
ts-rs = { version = "11.0.1", features = [
  "chrono-impl",
  "serde-compat",
  "serde-json-impl",
] }
validator = { version = "0.20.0", features = ["derive"] }

[lib]
name = "common"
path = "src/lib.rs"
