[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
dirs = "6.0.0"
flate2 = "1.1.2"
rmp-serde = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_with = { version = "3.14.0", features = ["chrono", "json", "macros"] }
ts-rs = { version = "11.0.1", features = [
  "chrono-impl",
  "serde-compat",
  "serde-json-impl",
] }
uuid = { version = "1.17.0", features = ["v4"] }
validator = { version = "0.20.0", features = ["derive"] }

[lib]
name = "common"
path = "src/lib.rs"
