[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
serde = "1.0.219"
validator = { version = "0.20.0", features = ["derive"] }

[lib]
name = "common"
path = "src/lib.rs"
