// This code was generated by Claude Opus 5
import type { Layer, Stroke } from "$lib/tauri/bindings";

export interface Point2D {
  x: number;
  y: number;
}

/**
 * An axis-aligned bounding box described by four coordinates, i.e. two
 * `(x, y)` pairs: `min` is the top-left corner, `max` is the bottom-right.
 */
export interface ContentBounds {
  min: Point2D;
  max: Point2D;
  width: number;
  height: number;
}

/** A uniform margin, or a per-side one. Missing sides default to `0`. */
export type Padding =
  number | { top?: number; right?: number; bottom?: number; left?: number };

/**
 * Collects every drawable stroke across the given layers, in draw order.
 * Hidden layers are skipped unless `includeHidden` is set, and empty
 * strokes are dropped.
 */
export function collectStrokes(
  layers: Layer[],
  includeHidden = false,
): Stroke[] {
  return layers
    .filter((l) => includeHidden || l.visible)
    .flatMap((l) => l.blocks)
    .map((b) => b.Stroke)
    .filter((s): s is Stroke => s != null && s.points.length > 0);
}

/** Builds a `ContentBounds` from the extent it spans. */
function boundsFromExtent(
  minX: number,
  minY: number,
  maxX: number,
  maxY: number,
): ContentBounds {
  return {
    min: { x: minX, y: minY },
    max: { x: maxX, y: maxY },
    width: maxX - minX,
    height: maxY - minY,
  };
}

/**
 * Finds the box enclosing a single stroke. Stroke thickness is taken into
 * account so the box covers the inked pixels, not just the centre line.
 *
 * Returns `null` for a stroke without points, which has no meaningful box.
 */
export function getStrokeBounds(stroke: Stroke): ContentBounds | null {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  const half = stroke.thickness / 2;
  for (const p of stroke.points) {
    if (p.x - half < minX) minX = p.x - half;
    if (p.y - half < minY) minY = p.y - half;
    if (p.x + half > maxX) maxX = p.x + half;
    if (p.y + half > maxY) maxY = p.y + half;
  }

  if (!Number.isFinite(minX)) return null;

  return boundsFromExtent(minX, minY, maxX, maxY);
}

/** Returns the smallest box containing both of the given ones. */
export function unionBounds(a: ContentBounds, b: ContentBounds): ContentBounds {
  return boundsFromExtent(
    Math.min(a.min.x, b.min.x),
    Math.min(a.min.y, b.min.y),
    Math.max(a.max.x, b.max.x),
    Math.max(a.max.y, b.max.y),
  );
}

/**
 * Finds the coordinate boundaries of the content: the smallest box
 * that encloses everything actually drawn.
 *
 * Coordinates are in the note's own (zoom/pan-independent) content space.
 * Returns `null` when there is nothing drawn.
 */
export function getContentBounds(
  layers: Layer[],
  options: { includeHidden?: boolean } = {},
): ContentBounds | null {
  return collectStrokes(
    layers,
    options.includeHidden,
  ).reduce<ContentBounds | null>((acc, stroke) => {
    const bounds = getStrokeBounds(stroke);
    if (!bounds) return acc;

    return acc ? unionBounds(acc, bounds) : bounds;
  }, null);
}

/**
 * Calculates a boundary around the given bounds by expanding it
 * with a margin. Accepts a single number for a uniform margin or an object
 * for per-side control. Returns a new `ContentBounds`.
 */
export function padBounds(
  bounds: ContentBounds,
  padding: Padding,
): ContentBounds {
  const p =
    typeof padding === "number"
      ? { top: padding, right: padding, bottom: padding, left: padding }
      : {
          top: padding.top ?? 0,
          right: padding.right ?? 0,
          bottom: padding.bottom ?? 0,
          left: padding.left ?? 0,
        };

  return boundsFromExtent(
    bounds.min.x - p.left,
    bounds.min.y - p.top,
    bounds.max.x + p.right,
    bounds.max.y + p.bottom,
  );
}

/**
 * Tests whether a circle overlaps a box, by comparing the squared distance
 * from its centre to the nearest point of the box against the squared radius.
 *
 * Used as a cheap rejection test: a box that misses cannot contain anything
 * the circle touches, so the exact test can be skipped entirely.
 */
export function circleIntersectsBounds(
  c: Point2D,
  radius: number,
  b: ContentBounds,
) {
  const dx = Math.max(b.min.x - c.x, 0, c.x - b.max.x);
  const dy = Math.max(b.min.y - c.y, 0, c.y - b.max.y);
  return dx * dx + dy * dy <= radius * radius;
}
