// This code was generated by Claude Sonnet 4.6
export interface FuzzyResult {
  item: string;
  score: number;
  indices: number[];
}

export function fuzzySearch(pattern: string, folders: string[]): FuzzyResult[] {
  if (!pattern) return folders.map((f) => ({ item: f, score: 0, indices: [] }));

  const results: FuzzyResult[] = [];
  const patternLower = pattern.toLowerCase();

  for (const folder of folders) {
    const folderLower = folder.toLowerCase();
    let patternIdx = 0;
    const indices: number[] = [];
    let bonus = 0;

    for (
      let i = 0;
      i < folderLower.length && patternIdx < patternLower.length;
      i++
    ) {
      if (folderLower[i] === patternLower[patternIdx]) {
        indices.push(i);
        // Reward consecutive matches
        if (patternIdx > 0 && indices[patternIdx - 1] === i - 1) bonus += 2;
        // Reward matches at segment boundaries (start of path or after /)
        if (i === 0 || folder[i - 1] === "/") bonus += 3;
        patternIdx++;
      }
    }

    // Only include if all pattern characters were matched
    if (patternIdx === patternLower.length) {
      const score = bonus / (folder.length + 1);
      results.push({ item: folder, score, indices });
    }
  }

  return results.sort((a, b) => b.score - a.score);
}
